/* GENERATED by scripts/build-tokens.mjs — do not edit.
   Source of truth: design/tokens.json. Run `npm run tokens` after changing it. */

export interface PaletteEntry {
  label: string;
  note: string;
  pop: string;
  'pop-hover': string;
  'on-pop': string;
  deep: string;
  'deep-hover': string;
  'on-deep': string;
  'mark-light': string;
  'mark-dark': string;
}

export const PALETTES = {
  'lime-slate': {
    'label': "Lime / Slate",
    'note': "Current. High-chroma chartreuse against a dark teal. The loudest of the four; strongest brand recall, least forgiving next to a warm logo.",
    'pop': "#d3f84f",
    'pop-hover': "#bbe434",
    'on-pop': "#2f4750",
    'deep': "#2f4750",
    'deep-hover': "#1e3138",
    'on-deep': "#d3f84f",
    'mark-light': "#2f4750",
    'mark-dark': "#d3f84f",
  },
  'amber-ink': {
    'label': "Amber / Ink",
    'note': "Warm orange against true black. The most conventional launch-board reading, and the friendliest backdrop for logos of any hue since black is not a colour anyone's brand competes with.",
    'pop': "#ffa552",
    'pop-hover': "#ee8730",
    'on-pop': "#111111",
    'deep': "#111111",
    'deep-hover': "#000000",
    'on-deep': "#ffa552",
    'mark-light': "#8a4a06",
    'mark-dark': "#ffa552",
  },
  'coral-ink': {
    'label': "Coral / Ink",
    'note': "Hot coral against black. Highest energy, reads editorial rather than corporate. Its mark tone is the darkest of the four, so link text sits quieter on the page.",
    'pop': "#ff6b6b",
    'pop-hover': "#f04a4a",
    'on-pop': "#111111",
    'deep': "#111111",
    'deep-hover': "#000000",
    'on-deep': "#ff6b6b",
    'mark-light': "#c2352f",
    'mark-dark': "#ff8f8f",
  },
  'lavender-midnight': {
    'label': "Lavender / Midnight",
    'note': "Pale violet against near-black indigo — both lifted from the palette image you sent earlier. The softest of the five: its bright block is the least saturated, so it competes with a logo less than lime or coral, but it also asserts itself least. Its dark block is nearly black, which means the hover has to go lighter rather than darker to stay visible.",
    'pop': "#b8a9fa",
    'pop-hover': "#a692f7",
    'on-pop': "#180f43",
    'deep': "#180f43",
    'deep-hover': "#332680",
    'on-deep': "#b8a9fa",
    'mark-light': "#5b46c9",
    'mark-dark': "#b8a9fa",
  },
  'cobalt-navy': {
    'label': "Cobalt / Navy",
    'note': "Sky blue against deep navy. The calmest option and the most obviously 'interface' — which cuts both ways: it never fights a logo, and it is the hue most likely to look like somebody else's brand.",
    'pop': "#74b9ff",
    'pop-hover': "#4a9ff0",
    'on-pop': "#111111",
    'deep': "#123a63",
    'deep-hover': "#0c2743",
    'on-deep': "#74b9ff",
    'mark-light': "#1a5c9e",
    'mark-dark': "#74b9ff",
  },
  'mono-ink': {
    'label': "Mono / Ink",
    'note': "No hue at all — black, white and the greys between. The interesting constraint is the bright block: because blocks are fixed across both themes, and monochrome has only value to work with, `pop` has to clear 3:1 on a white canvas AND on a near-black one. That leaves a band roughly #7f7f7f to #909090 and nothing else; anything lighter vanishes on white, anything darker vanishes on the dark canvas. So the loudest thing this palette can say is a mid grey, and every bit of emphasis has to come from the 1px border and the hard shadow instead of from colour. That is either the most honest version of this style or proof it needs a hue — which is the question worth looking at here.",
    'pop': "#8a8a8a",
    'pop-hover': "#7f7f7f",
    'on-pop': "#111111",
    'deep': "#1c1c1c",
    'deep-hover': "#333333",
    'on-deep': "#f2f2f2",
    'mark-light': "#5c5c5c",
    'mark-dark': "#a5a5a5",
  },
} as const satisfies Record<string, PaletteEntry>;

export type PaletteId = keyof typeof PALETTES;

/** The one shipping today. */
export const ACTIVE_PALETTE: PaletteId = 'lavender-midnight';

export const PALETTE_IDS = Object.keys(PALETTES) as PaletteId[];
