/* GENERATED by scripts/build-tokens.mjs — do not edit.
   Source of truth: design/tokens.json. Run `npm run tokens` after changing it. */

/** Deck's palette for the <canvas> share card, which has no stylesheet to read. */
export const PALETTE = {
  canvas: '#faf9f5',
  ink: '#111111',
  pop: '#b8a9fa',
  onPop: '#180f43',
  deep: '#180f43',
  onDeep: '#b8a9fa',
} as const;
