const fs = require('node:fs');
const path = require('node:path');
const { meta, sections } = require('./content.js');

/*
 * The handbook's third output: typed data the app imports, and the two
 * documents copied where Vite can serve them.
 *
 * This exists because the handbook was, in practice, unreachable. The PDF and
 * DOCX were written to the repository root and nothing ever linked to them —
 * no route, no footer entry, no `Frontend/public` for Vite to serve them out
 * of. The files were perfectly good and completely invisible: reported, fairly,
 * as "I can't find the handbook".
 *
 * Generating rather than hand-writing a page is the same argument that produced
 * `content.js` in the first place. A hand-kept fourth copy drifts, and this one
 * would drift worst of all — it is the copy people actually read, so it is the
 * copy nobody would think to check against the others.
 */
const ROOT = path.resolve(__dirname, '../..');
const DATA = path.join(ROOT, 'Frontend/src/data');
const PUBLIC = path.join(ROOT, 'Frontend/public');
const DOCS = ['Deck-Handbook.pdf', 'Deck-Handbook.docx'];

const q = (value) => JSON.stringify(value);

/*
 * The documents are copied rather than moved. The root copies are what somebody
 * cloning the repository expects to find, and `Frontend/public` is the only
 * place Vite will serve a static file from — so both have to exist, and the
 * copy has to happen here rather than being remembered.
 *
 * Sizes are measured here and written into the data. The page states them next
 * to the download links, and a hand-typed size is wrong the first time the
 * handbook grows a section.
 */
fs.mkdirSync(PUBLIC, { recursive: true });
const downloads = [];
for (const file of DOCS) {
  const from = path.join(ROOT, file);
  if (!fs.existsSync(from)) {
    console.warn(`skipped ${file} — not built yet. Run pdf.cjs and docx.cjs first.`);
    continue;
  }
  fs.copyFileSync(from, path.join(PUBLIC, file));
  downloads.push({
    file,
    kind: path.extname(file).slice(1).toUpperCase(),
    size: `${Math.round(fs.statSync(from).size / 1024)} KB`,
  });
}

const lines = [
  '/*',
  ' * Generated by `node scripts/handbook/web.cjs` — do not edit.',
  ' *',
  ' * The source is `scripts/handbook/content.js`, which also renders the PDF and',
  ' * the DOCX. Edit there and re-run, or the page and the documents disagree.',
  ' */',
  '',
  '/** A label and its explanation — rendered as a definition row. */',
  'export type HandbookFact = readonly [label: string, detail: string];',
  '',
  'export interface HandbookSection {',
  '  /** Positional, assigned at generation. Sections are never numbered by hand. */',
  '  readonly n: number;',
  '  readonly title: string;',
  '  readonly body: readonly string[];',
  '  readonly bullets: readonly HandbookFact[];',
  '}',
  '',
  'export const handbookMeta = {',
  `  title: ${q(meta.title)},`,
  `  subtitle: ${q(meta.subtitle)},`,
  `  generated: ${q(new Date().toISOString().slice(0, 10))},`,
  '  facts: [',
  ...meta.facts.map(([label, detail]) => `    [${q(label)}, ${q(detail)}],`),
  '  ],',
  '} as const satisfies {',
  '  title: string;',
  '  subtitle: string;',
  '  generated: string;',
  '  facts: readonly HandbookFact[];',
  '};',
  '',
  'export interface HandbookDownload {',
  '  readonly file: string;',
  '  readonly kind: string;',
  '  /** Measured at generation. Hand-written sizes are wrong by the next build. */',
  '  readonly size: string;',
  '}',
  '',
  'export const handbookDownloads: readonly HandbookDownload[] = [',
  ...downloads.map(
    (d) => `  { file: ${q(d.file)}, kind: ${q(d.kind)}, size: ${q(d.size)} },`,
  ),
  '];',
  '',
  'export const handbookSections: readonly HandbookSection[] = [',
];

sections.forEach((section, i) => {
  lines.push('  {');
  lines.push(`    n: ${i + 1},`);
  lines.push(`    title: ${q(section.title)},`);
  lines.push('    body: [');
  for (const paragraph of section.body ?? []) lines.push(`      ${q(paragraph)},`);
  lines.push('    ],');
  lines.push('    bullets: [');
  for (const [label, detail] of section.bullets ?? []) {
    lines.push(`      [${q(label)}, ${q(detail)}],`);
  }
  lines.push('    ],');
  lines.push('  },');
});

lines.push('];', '');

fs.mkdirSync(DATA, { recursive: true });
fs.writeFileSync(path.join(DATA, 'handbook.generated.ts'), lines.join('\n'), 'utf8');

console.log(
  `wrote Frontend/src/data/handbook.generated.ts \u00b7 ${sections.length} sections` +
    (downloads.length
      ? `\ncopied to Frontend/public: ${downloads.map((d) => `${d.file} ${d.size}`).join(' \u00b7 ')}`
      : ''),
);
