/**
 * Generates every consumer of design/tokens.json.
 *
 *   npm run tokens
 *
 * Four things need Deck's palette and none of them can read a CSS variable at
 * the moment they need one:
 *
 *   1. Tailwind's theme            — CSS, but also needs the per-palette
 *                                    override blocks the styleguide switches on
 *   2. The share card              — a <canvas>, which has no stylesheet
 *   3. The embeddable badge        — an SVG served into somebody else's page
 *   4. The handbook print stylesheet
 *
 * Each used to hold its own hand-copied hexes. That is how a palette revert
 * once restored the token names everywhere but left one file on the old values,
 * with nothing to catch it. Now they are all outputs.
 *
 * Generated files are committed, not gitignored: a fresh clone should build
 * without running a codegen step first, and the diff on a palette change is
 * exactly the point — you can see every consumer move together.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(join(root, 'design/tokens.json'), 'utf8'));

const BANNER = `/* GENERATED by scripts/build-tokens.mjs — do not edit.
   Source of truth: design/tokens.json. Run \`npm run tokens\` after changing it. */`;

const active = tokens.palettes[tokens.active];
if (!active) {
  throw new Error(`tokens.json: "active" is "${tokens.active}", which is not a palette`);
}

function write(relative, contents) {
  const target = join(root, relative);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, contents);
  console.log(`  ${relative}`);
}

/**
 * Writes a file that belongs to a *different repository*.
 *
 * The backend needs one generated palette file — the accents for the SVG badge
 * it serves into other people's pages, which cannot reach a stylesheet. It used
 * to be written directly, back when both halves lived under one root. They do
 * not any more: `Deck-Frontend` and `Deck-Backend` are separate repos that
 * happen to sit side by side on a development machine.
 *
 * So this writes it when the sibling checkout is there and says so clearly when
 * it is not, rather than the two failure modes either extreme would give —
 * crashing on a machine that only has the frontend, or silently conjuring a
 * `Backend/` directory inside the frontend repo and filling it with a file
 * nobody will ever read.
 *
 * The generated file is committed to the backend repo. It changes only when the
 * palette does, which is rare and deliberate, so a stale one is visible in a
 * diff rather than lurking.
 */
function writeSibling(repoDir, relative, contents) {
  const repo = join(root, '..', repoDir);
  if (!existsSync(repo)) {
    skipped.push(`${repoDir}/${relative}`);
    return;
  }
  const target = join(repo, relative);
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, contents);
  console.log(`  ../${repoDir}/${relative}`);
}

const skipped = [];

/* ------------------------------------------------------------ 1. Tailwind --- */

/**
 * The palette's tokens, as CSS custom properties.
 *
 * Emitted once for the active palette on `:root`, then again inside a
 * `[data-palette="..."]` block for every palette including the active one. The
 * repeat is deliberate: utilities compile to `var(--color-pop)`, so scoping an
 * override to an attribute on any ancestor re-colours everything beneath it.
 * That single fact is what makes live palette switching possible without a
 * rebuild, and it is why the styleguide can show four directions on one page.
 */
function paletteVars(palette, indent = '  ') {
  return [
    ['--pop', palette.pop],
    ['--pop-hover', palette['pop-hover']],
    ['--on-pop', palette['on-pop']],
    ['--deep', palette.deep],
    ['--deep-hover', palette['deep-hover']],
    ['--on-deep', palette['on-deep']],
  ]
    .map(([name, value]) => `${indent}${name}: ${value};`)
    .join('\n');
}

/**
 * Re-declares the Tailwind `--color-*` aliases wherever a base variable is
 * overridden below `:root`.
 *
 * This looks redundant and is not. `@theme` emits `--color-surface:
 * var(--surface)` onto `:root`, and a custom property holding a `var()` is
 * substituted at computed-value time *on the element that declares it* — so
 * `--color-surface` becomes the literal `#ffffff` there, and descendants
 * inherit that literal. Redefining `--surface` further down changes nothing,
 * because nothing re-runs the substitution.
 *
 * Site-wide dark mode never hit this: `.dark` goes on <html>, which *is* the
 * element `:root` matched, so the alias resolves against the dark value first
 * time. It only breaks when a theme or palette is scoped to a subtree — which
 * is exactly what the styleguide does to show two themes and four palettes on
 * one page. Re-declaring the alias forces a fresh substitution at that level.
 */
function aliases(names, indent = '  ') {
  return names.map((n) => `${indent}--color-${n}: var(--${n});`).join('\n');
}

const SURFACE_ALIASES = ['canvas', 'surface', 'surface-2', 'edge', 'accent'];
const PALETTE_ALIASES = ['pop', 'pop-hover', 'on-pop', 'deep', 'deep-hover', 'on-deep'];

const themedCss = `${BANNER}

@layer base {
  :root {
${Object.entries(tokens.neutrals.light)
  .map(([name, value]) => `    --${name}: ${value};`)
  .join('\n')}
    /* The accent as a *mark* — link text, focus rings, progress fills. Themed,
       because no fixed colour clears 4.5:1 against both canvases. */
    --accent: ${active['mark-light']};
${paletteVars(active, '    ')}
  }

  .dark {
${Object.entries(tokens.neutrals.dark)
  .map(([name, value]) => `    --${name}: ${value};`)
  .join('\n')}
    --accent: ${active['mark-dark']};
${aliases(SURFACE_ALIASES, '    ')}
    --color-body: var(--body-ink);
    --color-muted: var(--muted-ink);
  }

${Object.entries(tokens.palettes)
  .map(
    ([id, palette]) => `  /* ${palette.label} */
  [data-palette='${id}'] {
    --accent: ${palette['mark-light']};
${paletteVars(palette, '    ')}
    --color-accent: var(--accent);
${aliases(PALETTE_ALIASES, '    ')}
  }

  .dark [data-palette='${id}'],
  [data-palette='${id}'].dark {
    --accent: ${palette['mark-dark']};
    --color-accent: var(--accent);
  }`,
  )
  .join('\n\n')}
}

@theme {
  /* Themed surfaces and marks — resolve through the variables above. */
  --color-canvas: var(--canvas);
  --color-surface: var(--surface);
  --color-surface-2: var(--surface-2);
  --color-edge: var(--edge);
  --color-body: var(--body-ink);
  --color-muted: var(--muted-ink);
  --color-accent: var(--accent);

  /*
   * Role names, never hues. \`pop\` is the bright block whatever colour it
   * currently is and \`deep\` is the dark one, so a component written today
   * still says what it means after the palette changes. Each block carries its
   * own text colour: \`bg-pop text-on-pop\`, \`bg-deep text-on-deep\`.
   */
  --color-pop: var(--pop);
  --color-pop-hover: var(--pop-hover);
  --color-on-pop: var(--on-pop);
  --color-deep: var(--deep);
  --color-deep-hover: var(--deep-hover);
  --color-on-deep: var(--on-deep);

${Object.entries(tokens.fixed)
  .map(([name, value]) => `  --color-${name}: ${value};`)
  .join('\n')}

  /* Badge tones — and only badge tones. Exempt from the palette by design; see
     design/CONTRACT.md. The \`badge-\` prefix is the guard rail. */
${Object.entries(tokens.badges)
  .map(([name, value]) => `  --color-badge-${name}: ${value};`)
  .join('\n')}

  --shadow-pop: 4px 4px 0 var(--color-pop);
  --shadow-deep: 4px 4px 0 var(--color-deep);
}

/*
 * The select's drop arrow, spelled out per theme and per palette.
 *
 * It has to be a background-image: \`appearance: none\` removes the native arrow
 * and a pseudo-element cannot be placed inside a <select>. A data URI is an
 * opaque document with no access to the page's custom properties, so the fill
 * must be a literal — \`var(--accent)\` is not available to it. (A CSS mask over
 * the control was the other option and is worse: it clips the select's own text
 * along with the arrow.)
 *
 * Which is exactly why this is generated. Written by hand it was one more place
 * holding a hex that nothing would notice going stale.
 */
@layer components {
${Object.entries(tokens.palettes)
  .map(([id, palette]) => {
    const arrow = (hex) =>
      `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23${hex.slice(1)}'%3E%3Cpath d='M3 5.5h10L8 11.5z'/%3E%3C/svg%3E")`;
    const scope = id === tokens.active ? '' : `[data-palette='${id}'] `;
    return `  /* ${palette.label} */
  ${scope}.select-chevron {
    background-image: ${arrow(palette['mark-light'])};
    background-repeat: no-repeat;
    background-position: right 0.7rem center;
    background-size: 1rem;
  }

  .dark ${scope}.select-chevron,
  ${scope}.dark .select-chevron {
    background-image: ${arrow(palette['mark-dark'])};
  }`;
  })
  .join('\n\n')}
}
`;

write('src/styles/tokens.generated.css', themedCss);

/* ---------------------------------------------------------- 2. Share card --- */

write(
  'src/lib/palette.generated.ts',
  `${BANNER}

/** Deck's palette for the <canvas> share card, which has no stylesheet to read. */
export const PALETTE = {
  canvas: '${tokens.neutrals.light.canvas}',
  ink: '${tokens.fixed.ink}',
  pop: '${active.pop}',
  onPop: '${active['on-pop']}',
  deep: '${active.deep}',
  onDeep: '${active['on-deep']}',
} as const;
`,
);

/* ----------------------------------------------------------- 3. Workbench --- */

/*
 * The whole catalogue, for the styleguide's palette switcher.
 *
 * `/styleguide` used to import `design/tokens.json` directly, across the
 * directory boundary, which worked locally and broke the moment the frontend
 * was built anywhere the repository root was not present — a Vercel project
 * rooted at `Frontend/` never uploads `design/`, so `tsc` failed on a module it
 * could not find and then produced two more errors downstream, where
 * `keyof typeof tokens.palettes` had collapsed to `string | number | symbol`.
 *
 * Generating it instead makes `Frontend/` buildable on its own, which is the
 * property that actually matters, and types the ids properly on the way
 * through rather than needing a cast at every use.
 */
write(
  'src/lib/palettes.generated.ts',
  `${BANNER}

export interface PaletteEntry {
  label: string;
  note: string;
  pop: string;
  'pop-hover': string;
  'on-pop': string;
  deep: string;
  'deep-hover': string;
  'on-deep': string;
  'mark-light': string;
  'mark-dark': string;
}

export const PALETTES = {
${Object.entries(tokens.palettes)
  .map(
    ([id, palette]) => `  '${id}': {
${['label', 'note', 'pop', 'pop-hover', 'on-pop', 'deep', 'deep-hover', 'on-deep', 'mark-light', 'mark-dark']
  .map((key) => `    '${key}': ${JSON.stringify(palette[key] ?? '')},`)
  .join('\n')}
  },`,
  )
  .join('\n')}
} as const satisfies Record<string, PaletteEntry>;

export type PaletteId = keyof typeof PALETTES;

/** The one shipping today. */
export const ACTIVE_PALETTE: PaletteId = '${tokens.active}';

export const PALETTE_IDS = Object.keys(PALETTES) as PaletteId[];
`,
);

/* --------------------------------------------------------- 4. Embed badge --- */

writeSibling(
  'Backend',
  'src/config/palette.generated.ts',
  `${BANNER}

/**
 * Accents for the embeddable badge, which is an SVG served into somebody
 * else's page and so cannot reach Deck's stylesheet.
 *
 * Each carries its own ink: the two blocks sit at opposite ends of the
 * lightness scale, so the text colour is a property of the block, not a
 * constant the renderer can assume.
 */
export const ACCENTS: Record<string, { fill: string; ink: string }> = {
  pop: { fill: '${active.pop}', ink: '${active['on-pop']}' },
  deep: { fill: '${active.deep}', ink: '${active['on-deep']}' },
  grey: { fill: '${tokens.fixed.grey}', ink: '${tokens.fixed.ink}' },
};

export const DEFAULT_ACCENT = 'pop';
`,
);

/* ------------------------------------------------------------ 5. Handbook --- */

write(
  'docs/tokens.generated.css',
  `${BANNER}

:root {
${Object.entries(tokens.neutrals.light)
  .map(([name, value]) => `  --${name}: ${value};`)
  .join('\n')}
  --pop: ${active.pop};
  --pop-hover: ${active['pop-hover']};
  --on-pop: ${active['on-pop']};
  --deep: ${active.deep};
  --on-deep: ${active['on-deep']};
  --accent: ${active['mark-light']};
${Object.entries(tokens.fixed)
  .map(([name, value]) => `  --${name}: ${value};`)
  .join('\n')}
}
`,
);

if (skipped.length) {
  console.log(`\n  skipped (sibling repo not checked out here):`);
  for (const target of skipped) console.log(`    ${target}`);
  console.log('    — clone Deck-Backend alongside this repo and re-run to write it.');
}

console.log(
  `\n  Active palette: ${active.label} (${tokens.active}) · ${Object.keys(tokens.palettes).length} available\n`,
);
